### ISSUE TITLE
如果待翻译的句子中包含LaTeX编辑的公式

### ISSUE THREAD

**Issue by JR9124** [hichenway/RemoveLineBreakAndTranslate#1]
如果待翻译的句子中包含LaTeX编辑的公式，在网页版的百度翻译的时候不会出错，会有个结果，但是这个exe会得不到结果，请问怎么解决呢？

**Comment by lyshello123** [comment]
我的测试结果和网页版的百度翻译是一样的

**Comment by hichenway** [comment]
> 如果待翻译的句子中包含LaTeX编辑的公式，在网页版的百度翻译的时候不会出错，会有个结果，但是这个exe会得不到结果，请问怎么解决呢？

我的测试结果和网页版的百度翻译是一样的也，如果可以，你能把两者的对比结果发我邮箱嘛：lyshello123@163.com，谢谢
